label: Hario Theme
icon: bundles/hariocustomtheme/themes/customtheme/images/icon.png
# #logo: bundles/hariocustomtheme/themes/customtheme/images/ghostview.png
# styles:
#   - bundles/hariocustomtheme/themes/customtheme/css/style.css